CREATE TABLE KYSQR(
    QR_ID     VARCHAR(20) PRIMARY KEY,
    QR_TYPE   VARCHAR(10),
    QR_TEXT   VARCHAR(2000),
    MERCHANT_NAME VARCHAR(500),
    MERCHANT_CITY VARCHAR(100),
    AMOUNT    DECIMAL(7,2),
    TERMINAL_TYPE VARCHAR(20),
    INST_NUMBER INT,
    RRN       VARCHAR(10),
    CREATED_DATE TIMESTAMP
);

CREATE TABLE KYSQR_DETAIL (
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    QR_ID     VARCHAR(20),
    ENCRYPTED_CARD_DATA VARCHAR(100),
    ISSUER_ID VARCHAR(5),
    WALLET_ID VARCHAR(20),
    ECI VARCHAR(20),
    LOCATION_DATA  VARCHAR(50),
    STATUS    VARCHAR(1),
    REQUESTED_DATE DATE,
    FINISHED_DATE DATE
);

